name: Run init tests

on: [push]

jobs:
  run-unit-tests:
    name: Run Unit Tests
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      # Configurar o pnpm
      - name: Set up pnpm
        uses: pnpm/action-setup@v2
        with:
          version: '8'  # ou a versão específica que você está usando

      - name: Install dependencies with pnpm
        run: pnpm install

      - name: Run tests
        run: pnpm run test
